version: '3'

services:
    web0:
        image: momentsui
        container_name: momentsui01
        build:
          context: .
          dockerfile: moments.ui\Dockerfile
        ports:
            - "4200:80"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Docker
        volumes:
            -./vsdbg:/vsdbg
        restart: on-failure
        depends_on: 
            - web1
            - web2
            - web4
            - web5
    web1:
        image: momentsauthservice
        container_name: momentsauthservice01
        build:
          context: .
          dockerfile: moments.api\moments.auth\moments.auth.api\Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - NOTEDB=server=mssql;database=MomentsDB;User Id=sa;Password=1Secure*Password1;
        ports:
            - "8081:80"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Docker
        volumes:
            -./vsdbg:/vsdbg
        restart: on-failure
        depends_on: 
            - mssql
    web2:
        image: categoryservice
        container_name: categoryservice01
        build:
          context: .
          dockerfile: moments.api\moments.category\moments.category.api\Dockerfile
        ports:
            - "8091:80"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Docker
        volumes:
            -./vsdbg:/vsdbg
        restart: on-failure
        depends_on: 
            - db
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - Mongo_DB=mongodb://db:27017
    web4:
        image: momentsservice
        container_name: momentsservice01
        build:
          context: .
          dockerfile: moments.api\moments.space\moments.space.api\Dockerfile
        ports:
            - "8131:80"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Docker
        volumes:
            -./vsdbg:/vsdbg
        restart: on-failure
        depends_on: 
            - db
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - Mongo_DB=mongodb://db:27017
    web5:
        image: userservice
        container_name: userservice01
        build:
          context: .
          dockerfile: moments.api\moments.user\moments.user.api\Dockerfile
        ports:
            - "8121:80"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Docker
        volumes:
            -./vsdbg:/vsdbg
        restart: on-failure
        depends_on: 
            - db
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - Mongo_DB=mongodb://db:27017
    db:
        image: "mongo"
        ports:
            - "27017:27017"
    mssql:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: 1Secure*Password1
        ports:
            - "1433:1433"