name: Push Container to Heroku

on: 
  push:
    branches:
      - moments-space

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Heroku Container registry
      env: 
        working-directory: ./moments.api/moments.auth/moments.auth.api
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        working-directory: ${{ env.working-directory }} 
        heroku container:login 
    - name: Build and push
      env:
        working-directory: ./moments.api/moments.auth/moments.auth.api
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        working-directory: ${{ env.working-directory }}
        heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web 
    - name: Release
      env:
        working-directory: ./moments.api/moments.auth/moments.auth.api
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run:  |
        working-directory: ${{ env.working-directory }}
        heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web 
